import type { Organization } from './types'

export const ORGANIZATIONS: Organization[] = [
  {
    id: 1,
    name: "해운대청소년수련관",
    shortName: "해수련",
    description: "해운대 지역 청소년을 위한 다양한 체험·교육 프로그램을 운영하는 수련관",
    location: "부산시 해운대구",
    category: "요리·제빵",
    color: "#F59E0B",
    bgColor: "bg-amber-500",
    textColor: "text-amber-600",
    logo: "/logos/해운대청소년수련관.png",
  },
  {
    id: 2,
    name: "양정청소년수련관",
    shortName: "양정관",
    description: "디지털·공예 체험 중심의 청소년 활동 전문 수련관",
    location: "부산시 부산진구 양정동",
    category: "디지털·공예",
    color: "#8B5CF6",
    bgColor: "bg-violet-500",
    textColor: "text-violet-600",
    logo: "/logos/양정청소년수련관.png",
  },
  {
    id: 3,
    name: "해운대청소년문화의집",
    shortName: "해문의",
    description: "해운대 청소년들의 문화·예술 체험을 지원하는 열린 공간",
    location: "부산시 해운대구",
    category: "요리·제빵",
    color: "#EC4899",
    bgColor: "bg-pink-500",
    textColor: "text-pink-600",
    logo: "/logos/해운대청소년문화의집.jpg",
  },
  {
    id: 4,
    name: "금곡청소년수련관",
    shortName: "금곡관",
    description: "첨단 농업 기술 체험과 자연 친화 교육을 제공하는 수련관",
    location: "부산시 북구 금곡동",
    category: "스마트팜",
    color: "#22C55E",
    bgColor: "bg-green-500",
    textColor: "text-green-600",
    logo: "/logos/금곡청소년수련관.png",
  },
  {
    id: 5,
    name: "동래구청소년센터",
    shortName: "동래센",
    description: "AR·VR 기반 스포츠 체험과 디지털 활동을 운영하는 청소년 센터",
    location: "부산시 동래구",
    category: "스포츠·AR",
    color: "#3B82F6",
    bgColor: "bg-blue-500",
    textColor: "text-blue-600",
    logo: "/logos/동래구청소년센터.png",
  },
  {
    id: 6,
    name: "수영구청소년문화의집",
    shortName: "수영문",
    description: "힐링·놀이 문화 체험을 통해 청소년 정서를 지원하는 문화 공간",
    location: "부산시 수영구",
    category: "힐링·문화",
    color: "#14B8A6",
    bgColor: "bg-teal-500",
    textColor: "text-teal-600",
    logo: "/logos/수영구청소년문화의집.png",
  },
  {
    id: 7,
    name: "금련산청소년수련원",
    shortName: "금련산",
    description: "자연 속에서 과학·천체 체험을 할 수 있는 야외 수련원",
    location: "부산시 수영구 금련산",
    category: "과학·천체",
    color: "#6366F1",
    bgColor: "bg-indigo-500",
    textColor: "text-indigo-600",
    logo: "/logos/금련산청소년수련원.png",
  },
  {
    id: 8,
    name: "사하구청소년문화의집",
    shortName: "사하문",
    description: "스포츠와 디지털 창작 체험을 복합적으로 제공하는 문화의집",
    location: "부산시 사하구",
    category: "스포츠·디지털",
    color: "#EF4444",
    bgColor: "bg-red-500",
    textColor: "text-red-600",
    logo: "/logos/사하구청소년문화의집.png",
  },
  {
    id: 9,
    name: "부전청소년센터",
    shortName: "부전센",
    description: "3D 프린팅·바리스타 등 직업 체험형 프로그램을 운영하는 센터",
    location: "부산시 부산진구 부전동",
    category: "디지털·직업체험",
    color: "#F97316",
    bgColor: "bg-orange-500",
    textColor: "text-orange-600",
    logo: "/logos/부산진구부전청소년센터.png",
  },
  {
    id: 10,
    name: "북구청소년문화의집",
    shortName: "북구문",
    description: "미션형 탐험 활동으로 청소년 흥미와 역량을 키우는 문화의집",
    location: "부산시 북구",
    category: "탐험·문화",
    color: "#06B6D4",
    bgColor: "bg-cyan-500",
    textColor: "text-cyan-600",
    logo: "/logos/북구청소년문화의집.png",
  },
  {
    id: 11,
    name: "사상구청소년센터",
    shortName: "사상센",
    description: "환경·업사이클링 공예 체험을 통해 환경 감수성을 높이는 센터",
    location: "부산시 사상구",
    category: "환경·공예",
    color: "#84CC16",
    bgColor: "bg-lime-500",
    textColor: "text-lime-600",
    logo: "/logos/사상구청소년수련관.png",
  },
  {
    id: 12,
    name: "전포청소년센터",
    shortName: "전포센",
    description: "스포츠 클라이밍 전문 체험 시설을 갖춘 청소년 센터",
    location: "부산시 부산진구 전포동",
    category: "스포츠",
    color: "#E11D48",
    bgColor: "bg-rose-600",
    textColor: "text-rose-600",
    logo: "/logos/부산진구전포청소년센터.png",
  },
  {
    id: 13,
    name: "가야청소년센터",
    shortName: "가야센",
    description: "세계 각국의 요리 문화를 배우는 글로벌 청소년 센터",
    location: "부산시 부산진구 가야동",
    category: "요리·문화",
    color: "#D97706",
    bgColor: "bg-amber-600",
    textColor: "text-amber-700",
    logo: "/logos/부산진구가야청소년센터.png",
  },
  {
    id: 14,
    name: "서구청소년문화의집",
    shortName: "서구문",
    description: "다문화 요리 체험을 통해 세계 문화를 이해하는 문화의집",
    location: "부산시 서구",
    category: "요리·문화",
    color: "#DC2626",
    bgColor: "bg-red-600",
    textColor: "text-red-700",
    logo: "/logos/서구청소년문화의집.png",
  },
  {
    id: 15,
    name: "그랜드모먼트유스호스텔",
    shortName: "그랜드",
    description: "도시농업과 스마트팜 체험을 통해 미래 농업을 배우는 유스호스텔",
    location: "부산시 해운대구",
    category: "스마트팜",
    color: "#16A34A",
    bgColor: "bg-green-600",
    textColor: "text-green-700",
    logo: "/logos/그랜드모먼트 유스호스텔.png",
  },
  {
    id: 16,
    name: "아르피나",
    shortName: "아르피",
    description: "양궁·펜싱 등 정통 레저스포츠를 체험할 수 있는 청소년 시설",
    location: "부산시 기장군",
    category: "레저스포츠",
    color: "#2563EB",
    bgColor: "bg-blue-600",
    textColor: "text-blue-700",
    logo: "/logos/아르피나유스호스텔.jpg",
  },
  {
    id: 17,
    name: "금정청소년수련관",
    shortName: "금정관",
    description: "미디어·음악 제작 체험으로 청소년 창의력을 키우는 수련관",
    location: "부산시 금정구",
    category: "미디어·음악",
    color: "#9333EA",
    bgColor: "bg-purple-600",
    textColor: "text-purple-600",
    logo: "/logos/금정청소년수련관.png",
  },
]

export function getOrgById(id: number): Organization | undefined {
  return ORGANIZATIONS.find(o => o.id === id)
}
