import type { Organization, Program } from './types'

export const ORGANIZATIONS: Organization[] = [
  {
    id: 1,
    name: "해운대청소년수련관",
    shortName: "해수련",
    description: "해운대 지역 청소년을 위한 다양한 체험·교육 프로그램을 운영하는 수련관",
    location: "부산시 해운대구",
    category: "요리·제빵",
    color: "#F59E0B",
    bgColor: "bg-amber-500",
    textColor: "text-amber-600",
    logo: "/logos/해운대청소년수련관.png",
  },
  {
    id: 2,
    name: "양정청소년수련관",
    shortName: "양정관",
    description: "디지털·공예 체험 중심의 청소년 활동 전문 수련관",
    location: "부산시 부산진구 양정동",
    category: "디지털·공예",
    color: "#8B5CF6",
    bgColor: "bg-violet-500",
    textColor: "text-violet-600",
    logo: "/logos/양정청소년수련관.png",
  },
  {
    id: 3,
    name: "해운대청소년문화의집",
    shortName: "해문의",
    description: "해운대 청소년들의 문화·예술 체험을 지원하는 열린 공간",
    location: "부산시 해운대구",
    category: "요리·제빵",
    color: "#EC4899",
    bgColor: "bg-pink-500",
    textColor: "text-pink-600",
    logo: "/logos/해운대청소년문화의집.jpg",
  },
  {
    id: 4,
    name: "금곡청소년수련관",
    shortName: "금곡관",
    description: "첨단 농업 기술 체험과 자연 친화 교육을 제공하는 수련관",
    location: "부산시 북구 금곡동",
    category: "스마트팜",
    color: "#22C55E",
    bgColor: "bg-green-500",
    textColor: "text-green-600",
    logo: "/logos/금곡청소년수련관.png",
  },
  {
    id: 5,
    name: "동래구청소년센터",
    shortName: "동래센",
    description: "AR·VR 기반 스포츠 체험과 디지털 활동을 운영하는 청소년 센터",
    location: "부산시 동래구",
    category: "스포츠·AR",
    color: "#3B82F6",
    bgColor: "bg-blue-500",
    textColor: "text-blue-600",
    logo: "/logos/동래구청소년센터.png",
  },
  {
    id: 6,
    name: "수영구청소년문화의집",
    shortName: "수영문",
    description: "힐링·놀이 문화 체험을 통해 청소년 정서를 지원하는 문화 공간",
    location: "부산시 수영구",
    category: "힐링·문화",
    color: "#14B8A6",
    bgColor: "bg-teal-500",
    textColor: "text-teal-600",
    logo: "/logos/수영구청소년문화의집.png",
  },
  {
    id: 7,
    name: "금련산청소년수련원",
    shortName: "금련산",
    description: "자연 속에서 과학·천체 체험을 할 수 있는 야외 수련원",
    location: "부산시 수영구 금련산",
    category: "과학·천체",
    color: "#6366F1",
    bgColor: "bg-indigo-500",
    textColor: "text-indigo-600",
    logo: "/logos/금련산청소년수련원.png",
  },
  {
    id: 8,
    name: "사하구청소년문화의집",
    shortName: "사하문",
    description: "스포츠와 디지털 창작 체험을 복합적으로 제공하는 문화의집",
    location: "부산시 사하구",
    category: "스포츠·디지털",
    color: "#EF4444",
    bgColor: "bg-red-500",
    textColor: "text-red-600",
    logo: "/logos/사하구청소년문화의집.png",
  },
  {
    id: 9,
    name: "부전청소년센터",
    shortName: "부전센",
    description: "3D 프린팅·바리스타 등 직업 체험형 프로그램을 운영하는 센터",
    location: "부산시 부산진구 부전동",
    category: "디지털·직업체험",
    color: "#F97316",
    bgColor: "bg-orange-500",
    textColor: "text-orange-600",
    logo: "/logos/부산진구부전청소년센터.png",
  },
  {
    id: 10,
    name: "북구청소년문화의집",
    shortName: "북구문",
    description: "미션형 탐험 활동으로 청소년 흥미와 역량을 키우는 문화의집",
    location: "부산시 북구",
    category: "탐험·문화",
    color: "#06B6D4",
    bgColor: "bg-cyan-500",
    textColor: "text-cyan-600",
    logo: "/logos/북구청소년문화의집.png",
  },
  {
    id: 11,
    name: "사상구청소년센터",
    shortName: "사상센",
    description: "환경·업사이클링 공예 체험을 통해 환경 감수성을 높이는 센터",
    location: "부산시 사상구",
    category: "환경·공예",
    color: "#84CC16",
    bgColor: "bg-lime-500",
    textColor: "text-lime-600",
    logo: "/logos/사상구청소년수련관.png",
  },
  {
    id: 12,
    name: "전포청소년센터",
    shortName: "전포센",
    description: "스포츠 클라이밍 전문 체험 시설을 갖춘 청소년 센터",
    location: "부산시 부산진구 전포동",
    category: "스포츠",
    color: "#E11D48",
    bgColor: "bg-rose-600",
    textColor: "text-rose-600",
    logo: "/logos/부산진구전포청소년센터.png",
  },
  {
    id: 13,
    name: "가야청소년센터",
    shortName: "가야센",
    description: "세계 각국의 요리 문화를 배우는 글로벌 청소년 센터",
    location: "부산시 부산진구 가야동",
    category: "요리·문화",
    color: "#D97706",
    bgColor: "bg-amber-600",
    textColor: "text-amber-700",
    logo: "/logos/부산진구가야청소년센터.png",
  },
  {
    id: 14,
    name: "서구청소년문화의집",
    shortName: "서구문",
    description: "다문화 요리 체험을 통해 세계 문화를 이해하는 문화의집",
    location: "부산시 서구",
    category: "요리·문화",
    color: "#DC2626",
    bgColor: "bg-red-600",
    textColor: "text-red-700",
    logo: "/logos/서구청소년문화의집.png",
  },
  {
    id: 15,
    name: "그랜드모먼트유스호스텔",
    shortName: "그랜드",
    description: "도시농업과 스마트팜 체험을 통해 미래 농업을 배우는 유스호스텔",
    location: "부산시 해운대구",
    category: "스마트팜",
    color: "#16A34A",
    bgColor: "bg-green-600",
    textColor: "text-green-700",
    logo: "/logos/그랜드모먼트 유스호스텔.png",
  },
  {
    id: 16,
    name: "아르피나",
    shortName: "아르피",
    description: "양궁·펜싱 등 정통 레저스포츠를 체험할 수 있는 청소년 시설",
    location: "부산시 기장군",
    category: "레저스포츠",
    color: "#2563EB",
    bgColor: "bg-blue-600",
    textColor: "text-blue-700",
    logo: "/logos/아르피나유스호스텔.jpg",
  },
  {
    id: 17,
    name: "금정청소년수련관",
    shortName: "금정관",
    description: "미디어·음악 제작 체험으로 청소년 창의력을 키우는 수련관",
    location: "부산시 금정구",
    category: "미디어·음악",
    color: "#9333EA",
    bgColor: "bg-purple-600",
    textColor: "text-purple-600",
    logo: "/logos/금정청소년수련관.png",
  },
]

export const PROGRAMS: Program[] = [
  // 1. 해운대청소년수련관
  {
    id: "prog-1-1",
    organization_id: 1,
    name: "제과제빵 빵실빵실",
    description: "직접 반죽하고 구워보는 달콤한 제과제빵 체험 프로그램",
    date: "2026-06-13",
    time: "15:00 ~ 17:00",
    capacity: 20,
    location: "해운대청소년수련관",
    target: "중학생",
  },

  // 2. 양정청소년수련관
  {
    id: "prog-2-1",
    organization_id: 2,
    name: "VR·AR이 머지?",
    description: "최신 VR·AR 기기를 직접 체험하며 가상현실과 증강현실의 원리를 배우는 프로그램",
    date: "2026-06-20",
    time: "10:00 ~ 12:00",
    capacity: 40,
    location: "양정청소년수련관",
    target: "청소년",
  },
  {
    id: "prog-2-2",
    organization_id: 2,
    name: "플라워 메이커",
    description: "꽃을 활용한 플로럴 공예 체험으로 감성과 창의력을 키우는 프로그램",
    date: "2026-06-27",
    time: "10:00 ~ 12:00",
    capacity: 40,
    location: "양정청소년수련관",
    target: "청소년",
  },

  // 3. 해운대청소년문화의집
  {
    id: "prog-3-1",
    organization_id: 3,
    name: "제과제빵 체험",
    description: "맛있는 빵과 과자를 직접 만들어보는 달콤한 제과제빵 체험",
    date: "2026-07-04",
    time: "10:00 ~ 12:00",
    capacity: 40,
    location: "해운대청소년문화의집",
    target: "초등 3~6학년",
  },

  // 4. 금곡청소년수련관
  {
    id: "prog-4-1",
    organization_id: 4,
    name: "스마트팜 체험",
    description: "ICT 기술을 활용한 첨단 스마트팜을 직접 체험하고 미래 농업을 배우는 프로그램",
    date: "2026-07-11",
    time: "10:00 ~ 12:00",
    capacity: 40,
    location: "금곡청소년수련관",
    target: "9~24세",
  },

  // 5. 동래구청소년센터
  {
    id: "prog-5-1",
    organization_id: 5,
    name: "AR피구 HADO 체험",
    description: "AR 기술을 접목한 혁신적인 스포츠 HADO로 즐기는 미래형 피구 체험",
    date: "2026-07-18",
    time: "14:00 ~ 16:00",
    capacity: 40,
    location: "동래구청소년센터",
    target: "청소년",
  },

  // 6. 수영구청소년문화의집
  {
    id: "prog-6-1",
    organization_id: 6,
    name: "수다방탈출 힐링프로젝트",
    description: "친구들과 함께 방탈출 미션을 해결하며 소통과 힐링을 동시에 경험하는 프로그램",
    date: "2026-07-29",
    time: "13:00 ~ 15:00",
    capacity: 20,
    location: "수영구청소년문화의집",
    target: "초등 4~6학년",
  },

  // 7. 금련산청소년수련원
  {
    id: "prog-7-1",
    organization_id: 7,
    name: "우주여행! 천체관측",
    description: "금련산 자연 속에서 별자리와 행성을 관측하는 1박 2일 천체관측 캠프",
    date: "2026-08-08",
    time: "1박 2일 (토~일)",
    capacity: 40,
    location: "금련산청소년수련원",
    target: "청소년",
  },

  // 8. 사하구청소년문화의집
  {
    id: "prog-8-1",
    organization_id: 8,
    name: "스포츠클라이밍 오르樂",
    description: "실내 클라이밍 벽을 오르며 도전과 극복의 즐거움을 배우는 스포츠 체험",
    date: "2026-08-08",
    time: "10:00 ~ 12:00",
    capacity: 40,
    location: "사하구청소년문화의집",
    target: "청소년",
  },
  {
    id: "prog-8-2",
    organization_id: 8,
    name: "디지털드로잉 똑띠공작소",
    description: "태블릿과 디지털 툴을 활용해 나만의 작품을 만드는 디지털 드로잉 체험",
    date: "2026-09-19",
    time: "10:00 ~ 12:00",
    capacity: 40,
    location: "사하구청소년문화의집",
    target: "청소년",
  },
  {
    id: "prog-8-3",
    organization_id: 8,
    name: "디지털드로잉 똑띠공작소",
    description: "태블릿과 디지털 툴을 활용해 나만의 작품을 만드는 디지털 드로잉 체험",
    date: "2026-10-31",
    time: "10:00 ~ 12:00",
    capacity: 40,
    location: "사하구청소년문화의집",
    target: "청소년",
  },

  // 9. 부전청소년센터
  {
    id: "prog-9-1",
    organization_id: 9,
    name: "3D프린터 체험",
    description: "3D 모델링부터 프린팅까지 직접 체험하며 미래 제조 기술을 배우는 프로그램",
    date: "2026-08-04",
    time: "10:00 ~ 12:00",
    capacity: 40,
    location: "부전청소년센터",
    target: "청소년",
  },
  {
    id: "prog-9-2",
    organization_id: 9,
    name: "바리스타 체험",
    description: "커피의 역사와 제조 과정을 배우고 직접 음료를 만들어보는 바리스타 직업 체험",
    date: "2026-08-06",
    time: "10:00 ~ 12:00",
    capacity: 40,
    location: "부전청소년센터",
    target: "청소년",
  },

  // 10. 북구청소년문화의집
  {
    id: "prog-10-1",
    organization_id: 10,
    name: "미션! 문화의집 대탐험",
    description: "문화의집 곳곳을 탐험하며 미션을 수행하는 신나는 탐험 체험 프로그램",
    date: "2026-08-22",
    time: "10:00 ~ 12:00",
    capacity: 30,
    location: "북구청소년문화의집",
    target: "청소년",
  },

  // 11. 사상구청소년센터
  {
    id: "prog-11-1",
    organization_id: 11,
    name: "업사이클링 키링만들기",
    description: "버려지는 소재를 활용해 나만의 키링을 만드는 환경 친화적 공예 체험",
    date: "2026-08-29",
    time: "10:00 ~ 12:00",
    capacity: 20,
    location: "사상구청소년센터",
    target: "청소년",
  },

  // 12. 전포청소년센터
  {
    id: "prog-12-1",
    organization_id: 12,
    name: "도전! 스포츠클라이밍",
    description: "실내 클라이밍 벽을 오르며 자신의 한계를 극복하는 스포츠 클라이밍 체험",
    date: "2026-09-05",
    time: "10:00 ~ 12:00",
    capacity: 40,
    location: "전포청소년센터",
    target: "청소년",
  },

  // 13. 가야청소년센터 (8/29~9/19 매주 토)
  {
    id: "prog-13-1",
    organization_id: 13,
    name: "세계요리 만들기 (1회)",
    description: "세계 각국의 다양한 요리를 직접 만들어보며 글로벌 식문화를 체험하는 프로그램 (1회차)",
    date: "2026-08-29",
    time: "10:00 ~ 12:00",
    capacity: 40,
    location: "가야청소년센터",
    target: "청소년",
  },
  {
    id: "prog-13-2",
    organization_id: 13,
    name: "세계요리 만들기 (2회)",
    description: "세계 각국의 다양한 요리를 직접 만들어보며 글로벌 식문화를 체험하는 프로그램 (2회차)",
    date: "2026-09-05",
    time: "10:00 ~ 12:00",
    capacity: 40,
    location: "가야청소년센터",
    target: "청소년",
  },
  {
    id: "prog-13-3",
    organization_id: 13,
    name: "세계요리 만들기 (3회)",
    description: "세계 각국의 다양한 요리를 직접 만들어보며 글로벌 식문화를 체험하는 프로그램 (3회차)",
    date: "2026-09-12",
    time: "10:00 ~ 12:00",
    capacity: 40,
    location: "가야청소년센터",
    target: "청소년",
  },
  {
    id: "prog-13-4",
    organization_id: 13,
    name: "세계요리 만들기 (4회)",
    description: "세계 각국의 다양한 요리를 직접 만들어보며 글로벌 식문화를 체험하는 프로그램 (4회차)",
    date: "2026-09-19",
    time: "10:00 ~ 12:00",
    capacity: 40,
    location: "가야청소년센터",
    target: "청소년",
  },

  // 14. 서구청소년문화의집
  {
    id: "prog-14-1",
    organization_id: 14,
    name: "일본요리 만들기",
    description: "일본의 대표 요리를 직접 만들어보며 일본 식문화를 체험하는 요리 프로그램",
    date: "2026-10-10",
    time: "10:00 ~ 12:00",
    capacity: 40,
    location: "서구청소년문화의집",
    target: "청소년",
  },

  // 15. 그랜드모먼트유스호스텔
  {
    id: "prog-15-1",
    organization_id: 15,
    name: "도시농부 유스팜 스마트팜",
    description: "도심 속 스마트팜에서 씨앗부터 수확까지 직접 경험하는 도시농업 체험",
    date: "2026-10-17",
    time: "10:00 ~ 12:00",
    capacity: 20,
    location: "그랜드모먼트유스호스텔",
    target: "청소년",
  },

  // 16. 아르피나
  {
    id: "prog-16-1",
    organization_id: 16,
    name: "양궁·펜싱 레저스포츠",
    description: "양궁과 펜싱을 직접 체험하며 집중력과 체력을 동시에 키우는 레저스포츠 프로그램",
    date: "2026-10-24",
    time: "10:00 ~ 12:00",
    capacity: 40,
    location: "아르피나",
    target: "청소년",
  },

  // 17. 금정청소년수련관
  {
    id: "prog-17-1",
    organization_id: 17,
    name: "뮤직비디오 제작 뮤직ON-AIR",
    description: "기획·촬영·편집까지 나만의 뮤직비디오를 직접 제작하는 미디어 창작 체험",
    date: "2026-10-31",
    time: "10:00 ~ 13:00",
    capacity: 20,
    location: "금정청소년수련관",
    target: "청소년",
  },
]

export function getProgramsByOrg(organizationId: number): Program[] {
  return PROGRAMS.filter(p => p.organization_id === organizationId)
}

export function getOrgById(id: number): Organization | undefined {
  return ORGANIZATIONS.find(o => o.id === id)
}

export function getProgramById(id: string): Program | undefined {
  return PROGRAMS.find(p => p.id === id)
}
